name: recsys_training
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.23
  - ipython=7.22.0
  - jupyterlab=3.0.14
  - lightfm=1.16
  - matplotlib=3.3.4
  - notebook=6.3.0
  - numpy=1.20.1
  - pandas=1.2.4
  - pip=21.1
  - python=3.9.4
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - seaborn=0.11.1
  - setuptools=49.6.0
  - statsmodels=0.12.2
  - pip:
      - "--editable=git+https://github.com/coreylynch/pyFM#egg=pyfm"
      - tqdm==4.60.0
